template = "https://github.com/giellalt/template-lang-und"
rev_id = 265
template_sha = "55c74340aa57ef2b38d3f84b2a9790e969781f56"

[replacements]
__GLOTTOLOG_ID__ = "toke1240"
__LICENSE__ = "LGPLv3"
__REPO__ = "lang-tkl"
__UND2C__ = "tkl"
__UNDEFINED__ = "Tokelauan"
__UND__ = "tkl"
