template = "https://github.com/giellalt/template-lang-und"
rev_id = 270
template_sha = "a0e776e00408c682c6560029f0fded3c700e0e63"

[replacements]
__GLOTTOLOG_ID__ = "toke1240"
__LICENSE__ = "LGPLv3"
__REPO__ = "lang-tkl"
__UND2C__ = "tkl"
__UNDEFINED__ = "Tokelauan"
__UND__ = "tkl"
